'use strict';
// Channel guidance only. No request is sent and no availability or extra is sold here.
(function () {
  let channel;
  const panel=document.querySelector('#guest-option-panel');
  const copy={
    en:{directTitle:'Make more time for Montreux.',direct:'Use the contact in your reservation confirmation to ask about extra nights or late checkout. Your host will confirm availability, any additional tourist tax, the total price and payment terms before you decide.',directLink:'Contact Our Team ↗',airbnbTitle:'Keep your Airbnb stay together.',airbnb:'For extra nights, open your Airbnb reservation and request a date change. Eligible reservations may offer an instant extension. Ask your host in Airbnb about late checkout; any optional fee is handled through Airbnb’s Resolution Center.',extendLink:'How to Extend Your Airbnb Stay ↗',lateLink:'Late Checkout on Airbnb ↗',bookingTitle:'Start with your existing reservation.',booking:'Open your Booking.com confirmation or app and contact the property about an extension or late checkout. Wait for confirmation of availability, the revised price and how the change will be recorded before making any payment.',bookingLink:'Open Booking.com ↗',note:'Requests depend on availability and the next guest’s arrival. No extension or late checkout is approved or paid for on this preview.',select:'Choose your booking channel to see the next step.',label:'Original booking channel'},
    fr:{directTitle:'Prenez encore un peu de temps à Montreux.',direct:'Utilisez le contact figurant dans votre confirmation pour demander des nuits supplémentaires ou un départ tardif. Votre hôte confirmera la disponibilité, les éventuelles taxes de séjour supplémentaires, le prix total et les conditions de paiement avant votre décision.',directLink:'Contactez Notre Équipe ↗',airbnbTitle:'Gardez votre séjour Airbnb dans la même réservation.',airbnb:'Pour des nuits supplémentaires, ouvrez votre réservation Airbnb et demandez un changement de dates. Certaines réservations permettent une prolongation instantanée. Demandez à votre hôte sur Airbnb un départ tardif ; les frais optionnels passent par le Centre de résolution Airbnb.',extendLink:'Comment Prolonger Votre Séjour Airbnb ↗',lateLink:'Départ Tardif sur Airbnb ↗',bookingTitle:'Partez de votre réservation existante.',booking:'Ouvrez votre confirmation ou l’application Booking.com et contactez l’établissement pour une prolongation ou un départ tardif. Attendez la confirmation de la disponibilité, du prix modifié et de l’enregistrement du changement avant tout paiement.',bookingLink:'Ouvrir Booking.com ↗',note:'Les demandes dépendent de la disponibilité et de l’arrivée du prochain voyageur. Aucune prolongation ni aucun départ tardif n’est approuvé ou payé dans cet aperçu.',select:'Choisissez votre canal de réservation pour connaître la prochaine étape.',label:'Canal de réservation initial'},
    de:{directTitle:'Nehmen Sie sich mehr Zeit für Montreux.',direct:'Fragen Sie über den Kontakt in Ihrer Buchungsbestätigung nach zusätzlichen Nächten oder einer späteren Abreise. Ihr Gastgeber bestätigt Verfügbarkeit, zusätzliche Kurtaxen, Gesamtpreis und Zahlungsbedingungen, bevor Sie entscheiden.',directLink:'Unser Team Kontaktieren ↗',airbnbTitle:'Halten Sie Ihren Airbnb-Aufenthalt in einer Buchung.',airbnb:'Öffnen Sie für zusätzliche Nächte Ihre Airbnb-Buchung und beantragen Sie eine Datumsänderung. Bei berechtigten Buchungen ist eine sofortige Verlängerung möglich. Fragen Sie Ihren Gastgeber in Airbnb nach einem späten Check-out; optionale Gebühren werden über das Airbnb-Mediations-Center abgewickelt.',extendLink:'So Verlängern Sie Ihren Airbnb-Aufenthalt ↗',lateLink:'Später Check-out bei Airbnb ↗',bookingTitle:'Beginnen Sie mit Ihrer bestehenden Buchung.',booking:'Öffnen Sie Ihre Bestätigung oder die Booking.com-App und kontaktieren Sie die Unterkunft wegen einer Verlängerung oder späteren Abreise. Warten Sie vor einer Zahlung auf die Bestätigung der Verfügbarkeit, des neuen Preises und der Erfassung der Änderung.',bookingLink:'Booking.com Öffnen ↗',note:'Anfragen hängen von der Verfügbarkeit und der Anreise des nächsten Gastes ab. In dieser Vorschau wird keine Verlängerung oder spätere Abreise genehmigt oder bezahlt.',select:'Wählen Sie Ihren Buchungskanal, um den nächsten Schritt zu sehen.',label:'Ursprünglicher Buchungskanal'},
    es:{"directTitle":"Disfrute un poco más de Montreux.","direct":"Utilice el contacto de su confirmación de reserva para preguntar por noches adicionales o una salida tardía. Antes de que decida, el anfitrión confirmará la disponibilidad, las tasas turísticas adicionales que correspondan, el precio total y las condiciones de pago.","directLink":"Contacte con nuestro equipo ↗","airbnbTitle":"Mantenga su estancia en la misma reserva de Airbnb.","airbnb":"Para añadir noches, abra su reserva de Airbnb y solicite un cambio de fechas. Las reservas que cumplan los requisitos pueden ofrecer una ampliación inmediata. Consulte con su anfitrión en Airbnb sobre una salida tardía; los cargos opcionales se tramitan a través del Centro de resoluciones de Airbnb.","extendLink":"Cómo ampliar su estancia en Airbnb ↗","lateLink":"Salida tardía en Airbnb ↗","bookingTitle":"Empiece por su reserva actual.","booking":"Abra su confirmación o la aplicación de Booking.com y contacte con el alojamiento para solicitar una ampliación o una salida tardía. Antes de realizar un pago, espere a que se confirme la disponibilidad, el precio actualizado y cómo quedará registrado el cambio.","bookingLink":"Abrir Booking.com ↗","note":"Las solicitudes dependen de la disponibilidad y de la llegada del siguiente huésped. En esta vista previa no se aprueba ni se paga ninguna ampliación o salida tardía.","select":"Elija el canal de su reserva para ver el siguiente paso.","label":"Canal de la reserva original"},
    zh:{"directTitle":"在蒙特勒，多留一点时间。","direct":"如需多住几晚或延迟退房，请使用预订确认信息中的联系方式提出请求。作决定前，房东将确认是否可安排、额外住宿税、总价和付款条件。","directLink":"联系我们的团队 ↗","airbnbTitle":"将 Airbnb 住宿保留在同一预订中。","airbnb":"如需多住几晚，请打开您的 Airbnb 预订并申请更改日期。符合条件的预订可能支持即时延长。请在 Airbnb 内向房东询问延迟退房；任何可选费用通过 Airbnb 调解中心处理。","extendLink":"了解如何延长 Airbnb 住宿 ↗","lateLink":"了解 Airbnb 延迟退房 ↗","bookingTitle":"从您现有的预订开始。","booking":"请打开 Booking.com 确认信息或应用，联系住宿方询问延长住宿或延迟退房。付款前，请等待住宿方确认是否可安排、新的价格以及如何记录这项修改。","bookingLink":"打开 Booking.com ↗","note":"是否可安排取决于空房情况及下一位住客的抵达时间。本预览不会批准延长住宿或延迟退房，也不会收取相关付款。","select":"请选择本次预订的渠道，了解下一步。","label":"原始预订渠道"}
  };
  const locale=()=>['en','fr','de','es','zh'].includes(document.querySelector('#language').value)?document.querySelector('#language').value:'en';
  const node=(tag,text)=>{const item=document.createElement(tag);item.textContent=text;return item;};
  function render(){const m=copy[locale()];panel.replaceChildren();document.querySelector('.guest-channel-buttons').setAttribute('aria-label',m.label);if(!channel){panel.append(node('p',m.select));return;}
    const title=channel==='direct'?m.directTitle:channel==='airbnb'?m.airbnbTitle:m.bookingTitle;
    panel.append(node('h4',title),node('p',m[channel]));
    const links=channel==='direct'?[[m.directLink,'https://jadore-montreux.holidayfuture.com/contact-us']]:channel==='airbnb'?[[m.extendLink,'https://www.airbnb.com/help/article/4198'],[m.lateLink,'https://www.airbnb.com/help/article/3433']]:[[m.bookingLink,'https://www.booking.com/']];
    for(const [label,href] of links){const link=node('a',label);link.href=href;link.target='_blank';link.rel='noopener noreferrer';panel.append(link);}const note=node('p',m.note);note.className='guest-option-note';panel.append(note);
  }
  document.querySelectorAll('[data-channel]').forEach(button=>button.addEventListener('click',()=>{channel=button.dataset.channel;document.querySelectorAll('[data-channel]').forEach(item=>{item.classList.toggle('active',item===button);item.setAttribute('aria-pressed',String(item===button));});render();}));
  document.querySelector('#language').addEventListener('change',render);render();
})();
